#!/bin/bash
# isikan Username dan password disini

# Check koneksi internet
x=`ping -c1 8.8.8.8 2>&1 | grep 100%`
if [ ! "$x" = "" ]; then
	echo "It's down!! Attempting to restart."
        ifup wwan && echo "wwan sukses restart." || echo "wwan gagal di restart."
echo melakukan koneksi ulang ke login page
sleep 10
# Check ip from isp
echo melakukan cek ip WAN
ipwan=$(ifconfig | grep -A 2 'wlan0' | awk '/inet addr/{print substr($2,6)}')
mac=$(ifconfig | grep -A 1 'wlan0' | awk '/^[a-z]/ { mac=$NF; next } /inet addr:/ { print mac }')
key=$(openssl rand -hex 2)
echo ip anda $ipwan
echo melakukan regsitrasi jaringan WMS
# Login ke WMS
echo Username anda $(uci get auto_wms.setting.user)
echo Password anda $(uci get auto_wms.setting.pass)
wget --post-data="username="$(uci get auto_wms.setting.user)"."$key"@wms.1253052950.000&password="$(uci get auto_wms.setting.pass)"" "https://welcome2.wifi.id/wms/auth/authnew/autologin/quarantine.php?ipc="$ipwan"&gw_id="$(uci get auto_wms.setting.gw_id)"&mac="$mac"&redirect=&wlan="$(uci get auto_wms.setting.wlan_id)"/"$(uci get auto_wms.setting.wlan_id1)"" -O /dev/null 
echo Login Sukses
fi
	   
