#!/bin/sh
case $1 in
"install")
cp -f auto_wms /usr/bin/
sleep 1
chmod 755 /usr/bin/auto_wms
opkg update
opkg install openssl-util

cat > /root/auto_wms <<\EOF
#!/bin/bash
# isikan Username dan password disini

# Check koneksi internet
x=`ping -c1 8.8.8.8 2>&1 | grep 100%`
if [ ! "$x" = "" ]; then
	echo "It's down!! Attempting to restart."
        ifup wwan && echo "wwan sukses restart." || echo "wan gagal di restart."
echo melakukan koneksi ulang ke login page
sleep 10
# Check ip from isp
echo melakukan cek ip WAN
ipwan=$(ifconfig | grep -A 2 'wlan0' | awk '/inet addr/{print substr($2,6)}')
mac=$(ifconfig | grep -A 1 'wlan0' | awk '/^[a-z]/ { mac=$NF; next } /inet addr:/ { print mac }')
key=$(openssl rand -hex 2)
echo ip anda $ipwan
echo melakukan regsitrasi jaringan WMS
# Login ke WMS
echo Username anda $(uci get auto_wms.setting.user)
echo Password anda $(uci get auto_wms.setting.pass)
wget --post-data="username="$(uci get auto_wms.setting.user)"."$key"@freeMS&password="$(uci get auto_wms.setting.pass)"" "https://welcome2.wifi.id/wms/auth/authnew/autologin/quarantine.php?ipc="$ipwan"&gw_id="$(uci get auto_wms.setting.gw_id)"&mac="$mac"&redirect=&wlan="$(uci get auto_wms.setting.wlan_id)"/"$(uci get auto_wms.setting.wlan_id1)"" -O /dev/null 
echo Login Sukses
fi
	   
EOF

cat > /etc/config/auto_wms << END
config global 'setting'
	option user 'rara1111'
	option pass 'rara1111'
	option gw_id 'WAG-D5-RKT'
	option wlan_id 'MLGDI00064'
	option wlan_id1 'TLK-WI32512066-0001'
	   
END

cat > /www/cgi-bin/autowms << END
#!/bin/sh

    echo "Content-type: text/html"
    echo ""
    echo "
<html>
<style type=\"text/css\">
/***************************************
TUBUH
***************************************/
body {
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
	background: #2f2f2f;
	/*
    background-repeat:no-repeat;
    background: -webkit-linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
    background: -moz-linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
    background: -ms-linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
    background: -o-linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
    background: linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
    background-position: fixed;
    background-attachment: fixed;
    background-repeat: center;*/
    margin: 0;
    width: 100%;
    height: auto;
    text-align:center;
	font-family: "tahoma";
	font-size: small;
}
/***************************************
FOOTER LINK
***************************************/
.footer{
	font-size:small;
	margin-top: 10px;
	min-height: 35px;
	max-height: 40px;
	position: fixed; 
	display:block;
	bottom:0%;
	width:100%;
	padding:5px;
	color: white;
	background-color: #2F2F2F;
}
/* unvisited link */
.footer a:link {
    color: white;
}

/* visited link */
.footer a:visited {
    color: white;
}

/* mouse over link */
.footer a:hover {
    color: #04A4D5;
}

/* selected link */
.footer a:active {
    color: white;
}
/***************************************
MAIN BOX
***************************************/
.main-box {
	transition: all 1.0s ease;
	-moz-border-radius:5px;
	-webkit-border-radius:5px;
	border-radius:5px;
	background-color: rgba(255,255,255,0.5);
	max-width:400px;
	min-width:300px;
	height:auto;
	margin-left: auto ;
	margin-right: auto ;
	margin-bottom:70px;
	padding:10px;
	border: 1px solid #dbd9ca;
	display: inline-block;
	word-wrap: break-word;
}
.header{
	width: 100%;
	height: auto;
	background-color: #071c4d;
	display: inline-block;
	-webkit-box-shadow: 2px 2px 4px 2px #000000;
	box-shadow: 2px 2px 4px 2px #000000;
}
.img-header{
	margin-top:20px;
	margin-bottom:20px;
}
/***************************************
LABEL/INPUT
***************************************/
.label {
  text-align: left;
 }
.text {
  width: 100%;
 }
pre {
  text-align: left;
 }

</style>
<head>
 <title>WMS Auto Login</title>
 <meta name='viewport' content='width=device-width; maximum-scale=1; minimum-scale=1;' />
<link rel='shortcut icon' type='image/png' href='../pulpstone/favicon.png'>
 <meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' />
</head>
<body>

</div>
<div class='img-header'>
<a href='http://pulpstone.pw' target='_blank'><img src='../pulpstone/images/pulpstone.png' width='250px' height='auto'></a>
</div>
"
USER=\$(uci get auto_wms.setting.user)
PASS=\$(uci get auto_wms.setting.pass)
GW=\$(uci get auto_wms.setting.gw_id)
WLAN=\$(uci get auto_wms.setting.wlan_id)
WLAN1=\$(uci get auto_wms.setting.wlan_id1)

get_post(){
     for qr in \$QUERY_STRING
     do          
          if [ "\${qr%%=*}" == "\$1" ];then              
              echo \${qr##*=}| sed 's/+/ /g' 
              break
          fi 
     done  
}
    if [ "\$REQUEST_METHOD" = POST ]; then
            read -t 3 QUERY_STRING
            QUERY_STRING=\$(echo \$QUERY_STRING | sed 's/&/ /g') 
            QUERY_STRING=\$(echo \$QUERY_STRING | sed 's/%3A/:/g')             
            
            if [ "\$(get_post update)" == "Update Config" ];then
                  USER=\$(get_post user)
                  PASS=\$(get_post pass)
				  GW=\$(get_post gw_id)
				  WLAN=\$(get_post wlan_id)
				  WLAN1=\$(get_post wlan_id1)
				  uci set auto_wms.setting.user=\$USER
				  uci set auto_wms.setting.pass=\$PASS
				  uci set auto_wms.setting.gw_id=\$GW
				  uci set auto_wms.setting.wlan_id=\$WLAN
				  uci set auto_wms.setting.wlan_id1=\$WLAN1
				  uci commit auto_wms
                  killall auto_wms
                  auto_wms &         
                  date > /tmp/auto_wms
                  echo "config update by user.." >> /tmp/auto_wms  
            fi
    fi
    echo "<div class=main-box>
    <h1>WMS Auto Login</h1>
	<h3>PULPSTONE OpenWrt</h3>
    <form method=\"post\">       
        <div class=label>Username :</div><input name=\"user\" class=text value=\"\$USER\"><br>
        <div class=label>Password :</div><input name=\"pass\" class=text value=\"\$PASS\"><br>
		<div class=label>GW ID :</div><input name=\"gw_id\" class=text value=\"\$GW\"><br>
		<div class=label>Wlan ID :</div><input name=\"wlan_id\" class=text value=\"\$WLAN\">/<input name=\"wlan_id1\" class=text value=\"\$WLAN1\"><br>
        <input type=\"submit\" name=\"update\" value=\"Update Config\">
        

    </form><hr>
    "
echo "<pre>"
    echo "</pre>
	<p> NB. Lakukan penambahan script Schedule di router </br>
	( * * * * * /bin/sh /root/auto_wms ) </p>
    </div>
	<div class='footer'>
	&copy <a style='text-decoration:none;' href='https://www.facebook.com/shandylovepholepel' target='_blank'><font color='yellow'>Shandy Rendhika</font></a> 2019 - Pulpstone OpenWrt 2017
</div>
   </body></html>"

END
sleep 1
chmod 755 /www/cgi-bin/autowms
echo "install auto_wms selesai"
echo "akses konfigurasi di http://ipserver//cgi-bin/autowms"
echo "terima kasih Mikodemos (PingLoop)"
echo "terima kasih Fuad Salim (Web Pulpstone)"
echo "Script Auto Login WMS by shandy rendhika"
echo "PEMBUAT VIDIO @adiadem YT Review Apa Saja"
  exit 0
;;
esac
#end
